Include "Modules\IO\Image.bb"

Type UpdatesWindow
	Field Window
	Field ImageBox
	Field LockButton
	Field LockLabel
End Type

Type UpdateFile
	Field Name$, Checksum
End Type

Global Updates.UpdatesWindow

; Loads the files list. Bound Name$ reads (260 = Windows MAX_PATH) so
; a corrupted or hostile-update Files.dat with a wild length prefix
; can't hang the server at boot. Files.dat is generated by the update
; tooling so legitimate entries fit easily; the cap is purely defense
; against malformed input.
Function LoadUpdateFiles()

	F = ReadFile("Data\Server Data\Files.dat")
	If F = 0 Then Return 0

		Files = 0
		While Eof(F) = False
			Files = Files + 1
			U.UpdateFile = New UpdateFile
			U\Name$ = ReadBoundedString$(F, 260)
			U\Checksum = ReadInt(F)
		Wend

	CloseFile(F)
	Return Files

End Function

; Creates the Updates window
Function CreateUpdatesWindow.UpdatesWindow()

	U.UpdatesWindow = New UpdatesWindow
	U\Window = CreateWindow("Updates", 530, 10, 300, 450, Desktop(), 1)
	CreateWindow("", 0, 0, 0, 0, 0, 1)

	U\LockButton = CreateButton("Unlock Updates Server", 10, ClientHeight(U\Window) - 50, ClientWidth(U\Window) - 20, 25, U\Window)
	;U\LockPanel = CreatePanel(0, 0, 50, 50, U\Window)
	;CentreGadget(U\LockPanel)
	;SetGadgetShape U\LockPanel, GadgetX(U\LockPanel), 300, 50, 50
	;SetPanelImage(U\LockPanel, "Data\Server Data\RedLight.bmp")

	; Create ImageBox with pointer to loaded image
	U\ImageBox = CreateImageBox((GadgetWidth(U\Window) / 2) - 25, 300, 50, 50, U\Window, CurrentDir() + "Data\Server Data\RedLight.bmp")

	L = CreateLabel("Updates Server Status:", (GadgetWidth(U\Window) / 2) - 55, 275, 110, 20, U\Window)

	Dat$ = "The updates server is locked. This means that no players" + Chr(10)
	Dat$ = Dat$ + "can join the game or download updates. Any players" + Chr(10)
	Dat$ = Dat$ + "currently in the game will be removed and must wait" + Chr(10)
	Dat$ = Dat$ + "until the server is unlocked before they can rejoin." + Chr(10)
	Dat$ = Dat$ + "This is to allow you to upload a game update without" + Chr(10)
	Dat$ = Dat$ + "players downloading at the same time, and receiving" + Chr(10)
	Dat$ = Dat$ + "old or corrupt files. Make sure you unlock the server" + Chr(10)
	Dat$ = Dat$ + "as soon as you have finished uploading any updates."
	U\LockLabel = CreateLabel(Dat$, 10, 10, 280, 200, U\Window, 3)

	Return U

End Function