#!/usr/bin/env bash
#
# Regenerates docs/protocol/index.md from:
#   * src/Modules/Packets.bb   -- the 56 Const P_* declarations
#   * src/Modules/ServerNet.bb -- `Case P_*` dispatch lines (server-side handlers)
#   * src/Modules/ClientNet.bb -- `Case P_*` dispatch lines (client-side handlers)
#
# Usage:
#   ./scripts/gen_packet_index.sh         # writes docs/protocol/index.md
#   ./scripts/gen_packet_index.sh --check # exits 1 if the doc is stale
#
# Phase 1 (this script): auto-generated INDEX listing every packet
# with handler line refs and direction. Each per-packet detail page
# at docs/protocol/packets/P_<Name>.md is hand-written and lives
# alongside; the index links into them when they exist and renders
# "(stub)" otherwise. Future phases will add prose / field layouts
# per packet without changing the index generator.
#
# Direction inference:
#   * Handler only in ServerNet.bb  -> C2S (client-to-server)
#   * Handler only in ClientNet.bb  -> S2C (server-to-client)
#   * Handlers in both              -> Both
#   * Neither (no Case)             -> Unused (commented-out / legacy)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKETS="$REPO_ROOT/src/Modules/Packets.bb"
SERVERNET="$REPO_ROOT/src/Modules/ServerNet.bb"
CLIENTNET="$REPO_ROOT/src/Modules/ClientNet.bb"
PACKETS_DIR="$REPO_ROOT/docs/protocol/packets"
OUTPUT="$REPO_ROOT/docs/protocol/index.md"

CHECK_MODE=0
if [ "${1:-}" = "--check" ]; then
    CHECK_MODE=1
fi

for f in "$PACKETS" "$SERVERNET" "$CLIENTNET"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f not found" >&2
        exit 2
    fi
done

mkdir -p "$(dirname "$OUTPUT")"

# Step 1: collect P_* names + numeric IDs from Packets.bb.
# Output: "ID|Name" lines (numerically sorted).
packets=$(awk '
    /^Const P_[A-Za-z][A-Za-z0-9]*[[:space:]]*=[[:space:]]*[0-9]+/ {
        # Strip leading "Const P_"
        line = $0
        sub(/^Const P_/, "", line)
        # Split on = and trim
        eq = index(line, "=")
        name = substr(line, 1, eq - 1)
        gsub(/[[:space:]]/, "", name)
        id = substr(line, eq + 1)
        gsub(/[[:space:]]/, "", id)
        print id "|" name
    }
' "$PACKETS" | sort -t'|' -k1,1n)

# Step 2: extract server-side handler line numbers ("Case P_*").
server_handlers=$(awk '
    /^[[:space:]]*Case P_[A-Za-z]/ {
        # Match: optional leading whitespace, Case, P_<name>
        line = $0
        sub(/^[[:space:]]*Case P_/, "", line)
        # name ends at first non-identifier char (space, comma, end-of-line)
        i = 1
        n = length(line)
        while (i <= n) {
            c = substr(line, i, 1)
            if (c !~ /[A-Za-z0-9_]/) break
            i++
        }
        name = substr(line, 1, i - 1)
        print name "|" NR
    }
' "$SERVERNET")

client_handlers=$(awk '
    /^[[:space:]]*Case P_[A-Za-z]/ {
        line = $0
        sub(/^[[:space:]]*Case P_/, "", line)
        i = 1
        n = length(line)
        while (i <= n) {
            c = substr(line, i, 1)
            if (c !~ /[A-Za-z0-9_]/) break
            i++
        }
        name = substr(line, 1, i - 1)
        print name "|" NR
    }
' "$CLIENTNET")

# Step 3: emit the markdown.
{
cat <<'HEADER'
# Wire-protocol reference

Generated by `scripts/gen_packet_index.sh` from
[`src/Modules/Packets.bb`](../../src/Modules/Packets.bb),
[`src/Modules/ServerNet.bb`](../../src/Modules/ServerNet.bb), and
[`src/Modules/ClientNet.bb`](../../src/Modules/ClientNet.bb). **Do not edit this
file by hand** — rerun the generator after touching any of those files.

This is the index of the 56 packet types the engine exchanges between server
and client. Per-packet detail pages (when they exist) cover sub-codes, field
layouts, and validation requirements. For the wire-encoding primitives and
handler conventions, see:

* [`encoding.md`](encoding.md) — `RCE_StrFromInt$` / `RCE_IntFromStr` /
  `ClampWorldCoord#` / length-prefixed strings.
* [`handler-conventions.md`](handler-conventions.md) — soft-fail discipline,
  bounds-then-deref, iterator-during-iteration, handle-Null discipline.

## Direction legend

| Code | Meaning |
|---|---|
| **C→S** | Client to server. Untrusted input; every handler must apply soft-fail and bounds-check disciplines. |
| **S→C** | Server to client. Trusted source; client handlers are reliability/latency-tolerance focused. |
| **Both** | Both directions implement a handler. Usually different sub-codes per side. |
| **Unused** | Constant declared but no live handler in either dispatch table. Candidates for removal. |

## Per-packet pages

Per-packet detail pages live under [`packets/`](packets/). When a page exists,
the "Detail" column links into it; otherwise it shows `—`. Filling out per-packet
pages is a per-iteration documentation task — see CONTRIBUTING.md.

---

## Catalog

| ID | Packet | Direction | Server handler | Client handler | Detail |
|---|---|---|---|---|---|
HEADER

# Build the table.
#
# The per-row lookups MUST NOT use `awk ... exit` to stop at the first
# match. Under `set -euo pipefail`, `exit` closes awk's stdin pipe while the
# upstream `echo` may still be writing, so `echo` takes SIGPIPE (status 141);
# pipefail propagates that to the command substitution and `set -e` then
# aborts this `while` subshell mid-iteration, truncating "$OUTPUT.new". The
# failure is intermittent (the race only fires when `echo` hasn't finished
# writing, i.e. under load) and silently produced a truncated docs/protocol/
# index.md plus a flaky `--check`. Instead, let awk drain all input and keep
# only the first match via a guard flag -- mirrors gen_bvm_reference.sh,
# whose awk has no `exit` and never raced.
echo "$packets" | while IFS='|' read -r id name; do
    server_line=$(echo "$server_handlers" | awk -F'|' -v n="$name" '$1 == n && !seen { print $2; seen = 1 }')
    client_line=$(echo "$client_handlers" | awk -F'|' -v n="$name" '$1 == n && !seen { print $2; seen = 1 }')

    # Direction
    if [ -n "$server_line" ] && [ -n "$client_line" ]; then
        dir="Both"
    elif [ -n "$server_line" ]; then
        dir="C→S"
    elif [ -n "$client_line" ]; then
        dir="S→C"
    else
        dir="Unused"
    fi

    # Server column
    if [ -n "$server_line" ]; then
        server_col="[ServerNet.bb:$server_line](../../src/Modules/ServerNet.bb#L$server_line)"
    else
        server_col="—"
    fi
    # Client column
    if [ -n "$client_line" ]; then
        client_col="[ClientNet.bb:$client_line](../../src/Modules/ClientNet.bb#L$client_line)"
    else
        client_col="—"
    fi

    # Detail page link if exists
    if [ -f "$PACKETS_DIR/P_$name.md" ]; then
        detail_col="[P_$name](packets/P_$name.md)"
    else
        detail_col="—"
    fi

    echo "| $id | \`P_$name\` | $dir | $server_col | $client_col | $detail_col |"
done

cat <<'FOOTER'

---

## See also

* [`encoding.md`](encoding.md) — wire-encoding primitives and conventions
* [`handler-conventions.md`](handler-conventions.md) — handler discipline patterns
* [`packets/`](packets/) — per-packet detail pages (incrementally filled)
* [`../modules/packets.md`](../modules/packets.md) — overview of packet routing in the engine
* [`../../src/Modules/Packets.bb`](../../src/Modules/Packets.bb) — the canonical declarations
* [`../../CLAUDE.md`](../../CLAUDE.md) — agent-facing dev guide, including wire encoding, soft-fail, bounds-check, handle-Null discipline
FOOTER
} > "$OUTPUT.new"

if [ "$CHECK_MODE" = "1" ]; then
    if [ -f "$OUTPUT" ] && diff -q "$OUTPUT" "$OUTPUT.new" > /dev/null 2>&1; then
        rm -f "$OUTPUT.new"
        exit 0
    else
        echo "STALE: $OUTPUT does not match the regenerated version." >&2
        echo "Run: ./scripts/gen_packet_index.sh" >&2
        diff -u "$OUTPUT" "$OUTPUT.new" >&2 || true
        rm -f "$OUTPUT.new"
        exit 1
    fi
fi

mv "$OUTPUT.new" "$OUTPUT"
echo "Wrote $OUTPUT"
